spring.config.import=optional:file:.env[.properties]

jwt.secret-key=${JWT_SECRET_KEY}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}